[package]
name = "orbital"
description = "The Orbital Windowing System and Compositor"
repository = "https://github.com/redox-os/orbital"
version = "0.1.0"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
orbclient = "0.3"
orbfont = "0.1"
orbimage = "0.1"
redox_event = { git = "https://github.com/redox-os/event.git" }
redox_syscall = "0.1"
serde = "0.9"
serde_derive = "0.9"
toml = "0.3"
